php_version="8.1"
bdd_name="nextcloud"
bdd_user="nextcloudusr"
bdd_password="P@ssw0rd"
domain="cloud.easyformer.local"
nextcloud_version="30.0.4"
nextcloud_admin_user="admin"
nextcloud_admin_password="P@ssw0rd"